service: cancer-prediction-api
frameworkVersion: "4"
configValidationMode: error

provider:
  name: aws
  runtime: python3.12
  region: ${opt:region, 'eu-west-3'}
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 15
  logRetentionInDays: 14
  tracing:
    lambda: true
  environment:
    STAGE: ${sls:stage}

  # --- HTTP API (API Gateway v2) ---
  httpApi:
    payload: '2.0'
    cors:
      allowedOrigins: ${self:custom.allowedOrigins}
      allowedHeaders:
        - Content-Type
      allowCredentials: false

  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256

  tags:
    Project: mlops-breast-cancer
    Service: cancer-prediction-api
    Stage: ${sls:stage}

# On exclut tout par défaut, puis on inclut ce qu’il faut par fonction
package:
  individually: true
  patterns:
    - '!**'
    - '!.git/**'
    - '!node_modules/**'
    - '!venv/**'
    - '!train-venv/**'
    - '!model-layer/**'
    - '!**/__pycache__/**'
    - '!**/*.ipynb'
    - '!**/*.csv'
    - '!**/*.parquet'
    - '!**/*.md'

custom:
  allowedOrigins:
    - https://form.mlopstheotiste.fr
    - ${env:AMPLIFY_URL, 'https://main.d1s8fkj9in84k5.amplifyapp.com'}

functions:
  # Santé
  health:
    handler: handler.health
    package:
      patterns:
        - handler.py
    events:
      - httpApi:
          path: /health
          method: get

  # Prédiction
  predict:
    handler: handler.predict
    package:
      patterns:
        - handler.py
        - model/*.joblib        # adapte si le nom/extension change
    timeout: 20
    events:
      - httpApi:
          path: /predict
          method: post
          # Validation du corps côté API Gateway (HTTP API)
          request:
            schemas:
              'application/json': ${file(schemas/predict.json)}

resources:
  Outputs:
    ServiceEndpoint:
      Description: HTTP API base URL
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: HttpApi
            - ".execute-api."
            - Ref: AWS::Region
            - ".amazonaws.com/"
            - ${sls:stage}
    HealthUrl:
      Description: Healthcheck URL
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: HttpApi
            - ".execute-api."
            - Ref: AWS::Region
            - ".amazonaws.com/"
            - ${sls:stage}
            - "/health"
    PredictUrl:
      Description: Predict URL
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: HttpApi
            - ".execute-api."
            - Ref: AWS::Region
            - ".amazonaws.com/"
            - ${sls:stage}
            - "/predict"
