service: cancer-prediction-api
frameworkVersion: "4"
configValidationMode: error

provider:
  name: aws
  runtime: python3.12
  region: ${opt:region, 'eu-west-3'}
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 15
  logRetentionInDays: 14
  tracing:
    lambda: true
  environment:
    STAGE: ${sls:stage}
  # Réglages REST API (v1)
  apiGateway:
    minimumCompressionSize: 1024
  logs:
    restApi:
      accessLogging: true
      executionLogging: true
      level: INFO
      fullExecutionData: false
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
  tags:
    Project: mlops-breast-cancer
    Service: cancer-prediction-api
    Stage: ${sls:stage}

# Exclure tout par défaut
package:
  individually: true
  patterns:
    - '!**'
    - '!.git/**'
    - '!node_modules/**'
    - '!venv/**'
    - '!train-venv/**'
    - '!model-layer/**'
    - '!**/__pycache__/**'
    - '!**/*.ipynb'
    - '!**/*.csv'
    - '!**/*.parquet'
    - '!**/*.md'

custom:
  allowedOrigins:
    - https://form.mlopstheotiste.fr
    - ${env:AMPLIFY_URL, 'https://main.d1s8fkj9in84k5.amplifyapp.com'}

functions:
  # /health : uniquement handler.py
  health:
    handler: handler.health
    package:
      patterns:
        - handler.py
    events:
      - http:
          path: health
          method: get
          cors: true

  # /predict : handler + modèle
  predict:
    handler: handler.predict
    package:
      patterns:
        - handler.py
        - model/*.joblib
    timeout: 20
    events:
      - http:
          path: predict
          method: post
          cors:
            origins: ${self:custom.allowedOrigins}
            headers:
              - Content-Type
            allowCredentials: false
          request:
            schemas:
              application/json:
                name: PredictRequest
                schema: ${file(schemas/predict.json)}

resources:
  # (Optionnel mais conseillé) CORS aussi sur erreurs 4XX/5XX côté Gateway
  Resources:
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type'"
    GatewayResponseDefault5XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: ApiGatewayRestApi
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type'"

  Outputs:
    ServiceEndpoint:
      Description: REST API base URL
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api."
            - Ref: AWS::Region
            - ".amazonaws.com/"
            - ${sls:stage}
    HealthUrl:
      Description: Healthcheck URL
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api."
            - Ref: AWS::Region
            - ".amazonaws.com/"
            - ${sls:stage}
            - "/health"
    PredictUrl:
      Description: Predict URL
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api."
            - Ref: AWS::Region
            - ".amazonaws.com/"
            - ${sls:stage}
            - "/predict"
