service: cancer-prediction-api
frameworkVersion: "4"


provider:
  name: aws
  runtime: python3.12
  region: eu-west-3
  memorySize: 1024
  timeout: 15
  versionFunctions: true

  # Observabilité
  logRetentionInDays: 30
  tracing:
    lambda: true
    apiGateway: true
  logs:
    httpApi: true                       # logs d’accès API Gateway (HTTP API v2)

  httpApi:
    cors:
      allowedOrigins: ["*"]
      allowedHeaders: ["Content-Type"]
      allowedMethods: ["GET", "POST", "OPTIONS"]

  environment:
    S3_BUCKET: mlopstheotiste-bucket       # <-- adapte si besoin
    MODEL_KEY: models/RandomForest.pkl     # <-- adapte si besoin

  iam:
    role:
      statements:
        # Lecture du modèle depuis S3
        - Effect: Allow
          Action: s3:GetObject
          Resource:
            - arn:aws:s3:::${self:provider.environment.S3_BUCKET}/${self:provider.environment.MODEL_KEY}
            - arn:aws:s3:::${self:provider.environment.S3_BUCKET}/models/*

        # (facultatif) X-Ray pour traces détaillées
        - Effect: Allow
          Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
          Resource: "*"

package:
  patterns:
    - "!**"              # exclure tout…
    - handler.py         # …sauf le code Lambda

functions:
  health:
    handler: handler.health
    timeout: 15
    layers:
      # ARNs des layers (numpy + scikit-learn) – adapte si besoin
      - arn:aws:lambda:eu-west-3:571600829584:layer:numpy-layer:2
      - arn:aws:lambda:eu-west-3:571600829584:layer:sklearn-layer:11
    events:
      - httpApi:
          path: /health
          method: GET

  predict:
    handler: handler.predict
    timeout: 15
    layers:
      # ARNs des layers (numpy + scikit-learn) – adapte si besoin
      - arn:aws:lambda:eu-west-3:571600829584:layer:numpy-layer:2
      - arn:aws:lambda:eu-west-3:571600829584:layer:sklearn-layer:11
    events:
      - httpApi:
          path: /predict
          method: POST


 # serverless.yml – extrait monitoring correctif (HTTP API)
custom:
  alerts:
    dashboards: true

    topics:
      alarm:
        topic: ${self:service}-${sls:stage}-alerts
        notifications:
          - protocol: email
            endpoint: ${env:ALERT_EMAIL, 'change-me@example.com'}

    definitions:
      lambdaErrors:
        namespace: AWS/Lambda
        metric: Errors
        threshold: 1
        statistic: Sum
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
        treatMissingData: notBreaching

      lambdaThrottles:
        namespace: AWS/Lambda
        metric: Throttles
        threshold: 1
        statistic: Sum
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
        treatMissingData: notBreaching

      apiGateway5xx:                 # <-- NOM DE LA DÉFINITION (libre)
        namespace: AWS/ApiGateway
        metric: 5XXError
        threshold: 1
        statistic: Sum
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
        treatMissingData: notBreaching
        # Dimensions pour **HTTP API** (v2)
        dimensions:
          - Name: ApiId
            Value:
              Ref: HttpApi          # référence CloudFormation du HttpApi créé par Serverless
          - Name: Stage
            Value: ${sls:stage}

    # On demande explicitement ces alarmes
    alarms:
      - lambdaErrors
      - lambdaThrottles
      - apiGateway5xx              # <-- on appelle la définition ci-dessus
         

