service: cancer-prediction-api
frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.11
  region: ${env:AWS_REGION, "eu-west-3"}
  stage: ${env:STAGE, "dev"}
  memorySize: 256
  timeout: 29
  logRetentionInDays: 14
  stackName: cancer-prediction-api-${sls:stage}
  apiGateway:
    # REST API (URL avec /dev)
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
    metrics: true
  environment:
    STAGE: ${sls:stage}

package:
  patterns:
    - "handler.py"
    - "model-layer/**"
    - "schemas/**"
    - "!node_modules/**"
    - "!venv/**"
    - "!ui/**"
    - "!**/*.md"

layers:
  model:
    path: model-layer
    name: model-layer-${sls:stage}
    compatibleRuntimes:
      - python3.11

functions:
  health:
    handler: handler.health
    events:
      - http:
          path: health
          method: get
          cors:
            origin: "${env:FORM_ORIGIN, 'https://form.mlopstheotiste.fr'}"
            headers:
              - Content-Type
            allowCredentials: false

  predict:
    handler: handler.predict
    memorySize: 512
    timeout: 30
    layers:
      - { Ref: ModelLambdaLayer }
    events:
      - http:
          path: predict
          method: post
          cors:
            origin: "${env:FORM_ORIGIN, 'https://form.mlopstheotiste.fr'}"
            headers:
              - Content-Type
            allowCredentials: false

plugins:
  - serverless-prune-plugin
  # (optionnel) décommente si tu utilises ce plugin :
  # - serverless-python-requirements

custom:
  prune:
    automatic: true
    number: 3

resources:
  Outputs:
    ServiceEndpoint:
      Description: "API base URL"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - { Ref: ApiGatewayRestApi }
            - ".execute-api."
            - { Ref: "AWS::Region" }
            - ".amazonaws.com/"
            - "${sls:stage}"
    HealthUrl:
      Description: "Healthcheck URL"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - { Ref: ApiGatewayRestApi }
            - ".execute-api."
            - { Ref: "AWS::Region" }
            - ".amazonaws.com/"
            - "${sls:stage}"
            - "/health"
    PredictUrl:
      Description: "Predict URL"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - { Ref: ApiGatewayRestApi }
            - ".execute-api."
            - { Ref: "AWS::Region" }
            - ".amazonaws.com/"
            - "${sls:stage}"
            - "/predict"
