functions:
  predict:
    handler: handler.predict
    events:
      - http:
          path: predict
          method: post
          cors:
            origins:
              - https://main.d1s8fkj9in84k5.amplifyapp.com
              - https://form.mlopstheotiste.fr
            headers:
              - Content-Type
            allowCredentials: false
  health:
    handler: handler.health
    events:
      - http:
          path: health
          method: get
          cors: true
